FROM oven/bun:1-alpine
WORKDIR /app

# Рекомендация Next.js для работы SWC/Turbopack на Alpine Linux
RUN apk add --no-cache libc6-compat

# Зависимости
COPY package.json bun.lock* ./
RUN bun install --frozen-lockfile || bun install

COPY . .

# Базовые настройки для dev-режима
ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

# HMR
ENV WATCHPACK_POLLING=true
ENV CHOKIDAR_USEPOLLING=true

EXPOSE 3000

CMD ["bun", "--bun", "run", "next", "dev", "--turbopack", "-H", "0.0.0.0", "-p", "3000"]